// <auto-generated />
namespace RecNote.WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class initial15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial15));
        
        string IMigrationMetadata.Id
        {
            get { return "201507251122141_initial15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
