//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecNote.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class IndexListView
    {
        public int ServiceTypeId { get; set; }

        [Key]
        public int ServiceId { get; set; }
        public string ApplicationUser_Id { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string Address { get; set; }
        public float InvoiceAmount { get; set; }
        public string InvoiceDate { get; set; }
        public string PayeeBank { get; set; }
        public string PaymentMethod { get; set; }
        public string ServiceTypeDescription { get; set; }
    }
}
