//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecNote.WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IndexListView> IndexListViews { get; set; }

        public System.Data.Entity.DbSet<RecNote.WebApp.Models.Maintenance> Maintenances { get; set; }

        public System.Data.Entity.DbSet<RecNote.WebApp.Models.MaintenanceType> MaintenanceTypes { get; set; }
    }
}
